Updated debian/ for dh7.
o Revised debian/ control files.
o Pulling 2.10 source, changes made since then by Markus, as well as
  patches by Jay Weisskopf (from GitHub).
o Setup to build from git repository as working directory using
  git-buildpackage.

diff --git a/debian/shellinabox.init b/debian/shellinabox.init
--- a/debian/shellinabox.init
+++ b/debian/shellinabox.init
@@ -7,9 +7,13 @@
 # Default-Stop:      0 1 6
 # Short-Description: Shell In A Box Daemon
 # Description:       Daemon for publishing a login shell at
-#                    http://localhost:4200
+#                    http://localhost:SHELLINABOX_PORT
+#		     where default port number is 4200. 
 ### END INIT INFO
 
+# Authors: Markus Gutschke <markus@shellinabox.com>, Marc Singer <elf@buici.com>
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
 PATH=/sbin:/bin:/usr/sbin:/usr/bin
 DESC="Shell In A Box Daemon"
 NAME="shellinabox"
@@ -17,13 +21,18 @@ DAEMON="/usr/bin/shellinaboxd"
 PIDFILE="/var/run/shellinaboxd.pid"
 SCRIPTNAME=/etc/init.d/$NAME
 
-# Gracefully exit if the package has been removed.
-test -x $DAEMON || exit 0
+# Exit if the package is not installed
+[ -x $DAEMON ] || exit 0
 
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
-
-# Include shellinabox defaults if available.
-test -f /etc/default/shellinabox && . /etc/default/shellinabox
 
 # Set some default values
 SHELLINABOX_DATADIR="${SHELLINABOX_DATADIR:-/var/lib/shellinabox}"
@@ -95,25 +104,38 @@ d_status() {
 
 case "$1" in
     start)
-        log_daemon_msg "Starting $DESC" "$NAME"
+        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
         d_start
-        log_end_msg $?
+        case "$?" in
+	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+	    2)   [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
         ;;
     stop)
-        log_daemon_msg "Stopping $DESC" "$NAME"
+        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
         d_stop
-        log_end_msg $?
+        case "$?" in
+	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+	    2)   [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
         ;;
     reload)
-        log_daemon_msg "Reloading services for $DESC" "$NAME"
+        [ "$VERBOSE" != no ] && log_daemon_msg "Reloading services for $DESC" "$NAME"
         d_reload
-        log_end_msg $?
+        case "$?" in
+	    0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+	    2)   [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	esac
         ;;
     restart|force-reload)
-        log_daemon_msg "Restarting $DESC" "$NAME"
+        [ "$VERBOSE" != no ] && log_daemon_msg "Restarting $DESC" "$NAME"
         d_stop
         d_start
-        log_end_msg $?
+        case "$?" in
+	    0) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+	    1) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+	    *) [ "$VERBOSE" != no ] && log_end_msg 1 ;; # Failed to start
+	esac
         ;;
     status)
         d_status
